### ISSUE TITLE
Upload project banner and project logo

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grant-hub#148]
From Grant Hub MVP Bug Bash form: https://docs.google.com/forms/d/1DquRIEYauMt5RB2tv46jAefLJ6uRgsfIc1gYANQ-DlY/edit?usp=sharing 

**Tasks**
- [ ] Add "upload background image" field at project level (TBD - Michelle currently confirming with Optimism) 
- [ ] Update lightning bolt to be project logo? Remove lightning bolt? 

Full Description: 

Not an issue just feedback from being involved in optimism partnership. There seems to be a desire to have a profile image and a banner. The photo you upload seems to be the banner image (not really clear what the photo was being uploaded for)

Then once you submit project you see the tile and the uploaded image is a banner, but you also then have this lightning icon. It would be cool if that could be turned into another photo you can upload and that be more of a PFP. That way it meets the needs/desires of Optimism

Again just a node of feedback from my experience in working with Optimism.

**Comment by michellema1208** [comment]
@willsputra would also love your feedback here! If we change this so that the project logo is where the lightning bolt icon is currently, would that be too small for a project logo display-wise? Wondering what the UX would look like here 

My preference would be to keep logo as the preview image on the Dashboard, remove the lightning bolt?, and have a new space for logo on the Project Details page. Open to thoughts though!

**Comment by willsputra** [comment]
@michellema1208 agree with removing the lightning bolt and having a bigger circle to place the logo instead!

Eduardo has these updated designs in Round Manager for projects, so I'll make it consistent on Grant Hub too:
![image](https://user-images.githubusercontent.com/19514207/178481224-4ba1f6fd-1632-4fa4-a81e-9598881a89ae.png)
![image](https://user-images.githubusercontent.com/19514207/178481276-f94c3099-67fd-4aaa-aae0-b59dcb9e44d4.png)
