### ISSUE TITLE
Create CTA for Grant Hub on cGrants platform

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grant-hub#28]
CTA for existing grant owners to move to Grants 2.0 during GR14 claims period

**Comment by schultztimothy** [comment]
@michellema1208 Do we know the url for grants hub will be?

**Comment by schultztimothy** [comment]
I'm going to move this back in to TODO since the integration has been delayed. here is the WIP branch for when these changes will be ready again: https://github.com/gitcoinco/web/tree/28-add-grant-hub-cta
