### ISSUE TITLE
Update Project details page

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grant-hub#75]
- [x] Add bottom whitespace for scroll 
- [x] Change copy to say Project Challenges
- [x] Add hyperlink for project website 
- [x] Add project creation date 
- [x] "My Projects" text in the upper left hand corner should take user back to home page

<img width="1192" alt="Screen Shot 2022-06-08 at 3 19 52 PM" src="https://user-images.githubusercontent.com/26017180/172699212-fec8939c-20fe-4b70-b53f-4ccf00d3182a.png">

**Comment by schultztimothy** [comment]
@michellema1208 is this referring to the Project details Text? "My Projects" text in the upper left hand corner should take user back to home page

**Comment by michellema1208** [comment]
Yes that's exactly it! @schultztimothy

**Comment by michellema1208** [comment]
@schultztimothy has this been merged already? I'm seeing the first task updated, but the other four tasks above are not reflected in the live demo

**Comment by michellema1208** [comment]
@schultztimothy on the Project Details page, let's update the copy of the second "project roadmap" question to say "Project Challenges"

**Comment by schultztimothy** [comment]
> @schultztimothy on the Project Details page, let's update the copy of the second "project roadmap" question to say "Project Challenges"

This should fix it 😄 https://github.com/gitcoinco/grant-hub/pull/154
